#weights: ./work_dir/HKEXtoSZSE/best_model.pt

weights: ./work_dir/HKEXtoSZSE/gru_best_model.pt
#weights: ./work_dir/HKEXtoSZSE/lstm_best_model.pt
#weights: ./work_dir/HKEXtoSZSE/stgcn_best_model.pt
#weights: ./work_dir/HKEXtoSZSE/sastgcn_best_model.pt
#weights: ./work_dir/HKEXtoSZSE/rtgcn_best_model.pt
#weights: ./work_dir/HKEXtoSZSE/dygcngru_best_model.pt
#weights: ./work_dir/HKEXtoSZSE/dygcngruae_best_model.pt
#weights: ./work_dir/HKEXtoSZSE/highloss_best_model.pt
# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/HKEXtoSZSE/test_15_EOD.npy
  price_path: ./data/HKEXtoSZSE/test_15_price.npy
  label_path: ./data/HKEXtoSZSE/test_15_label.pkl
  adj_path: ./data/HKEXtoSZSE/adj_test_15.npz
#=================================================
#test_feeder_args:
#  data_path: ./data/t=5/SZSE/test_15_EOD.npy
#  price_path: ./data/t=5/SZSE/test_15_price.npy
#  label_path: ./data/t=5/SZSE/test_15_label.pkl
#  adj_path: ./data/t=5/SZSE/test_15_adj.npz
# model
model: net.benchmarkmodel.GRU
#model: net.benchmarkmodel.LSTM3
#model: net.st_gcn.STGCN2
#model: net.SASTGCN.SASTGCN
#model: net.benchmarkmodel.Model_rt_gcn
#model: net.withoutdynet_rtgcn.STGCN_withoutdynet
#model: net.rt_gcn.STGCN
#model: net.rt_gcn.STGCN_wofe
#model: net.rt_gcn.STGCN_withAE
model_args:
  in_channels: 4
  dropout: 0
  hidden: 8
  hidden2: 4
  out_channels: 4
  kernel: 1
  stride: 1
  # edge_importance_weighting: True
#  edge_importance_weighting: 'Uniform'
  graph_args:
    market: 'HKEXtoSZSE'
    relation_path: ./data/HKEXtoSZSE/adjmx_amount_HKEXtoSZSE.pkl
    strategy: 'uniform'

# test 
phase: test
device: 0
test_batch_size: 64


# seed
seed: 8