#weights: ./work_dir/HKEXtoSSE/best_model.pt
#weights: ./data/t=5/SSE/best_model.pt

weights: ./work_dir/HKEXtoSSE/gru_best_model.pt
#weights: ./work_dir/HKEXtoSSE/lstm_best_model.pt
#weights: ./work_dir/HKEXtoSSE/stgcn_best_model.pt
#weights: ./work_dir/HKEXtoSSE/sastgcn_best_model.pt
#weights: ./work_dir/HKEXtoSSE/rtgcn_best_model.pt
#weights: ./work_dir/HKEXtoSSE/dygcngru_best_model.pt
#weights: ./work_dir/HKEXtoSSE/dygcngruae_best_model.pt
#weights: ./work_dir/HKEXtoSSE/balance_best_model.pt
#weights: ./work_dir/HKEXtoSSE/caselow_best_model.pt
# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/HKEXtoSSE/test_15_EOD.npy
  price_path: ./data/HKEXtoSSE/test_15_price.npy
  label_path: ./data/HKEXtoSSE/test_15_label.pkl
  adj_path: ./data/HKEXtoSSE/adj_test_15.npz
#================================================= casestudy时记得修改rtgcn中的num_nodes
#test_feeder_args:
#  data_path: ./data/casestudy/test_15_EOD.npy
#  price_path: ./data/casestudy/test_15_price.npy
#  label_path: ./data/casestudy/test_15_label.pkl
#  adj_path: ./data/casestudy/test_15_adj.npz
# model
model: net.benchmarkmodel.GRU
#model: net.benchmarkmodel.LSTM3
#model: net.st_gcn.STGCN
#model: net.SASTGCN.SASTGCN
#model: net.benchmarkmodel.Model_rt_gcn
#model: net.withoutdynet_rtgcn.STGCN_withoutdynet
#model: net.rt_gcn.STGCN
#model: net.rt_gcn.STGCN_wofe
#model: net.rt_gcn.STGCN_withAE
model_args:
  in_channels: 4
  dropout: 0
  hidden: 8
  hidden2: 4
  out_channels: 4
  kernel: 1
  stride: 1
  # edge_importance_weighting: True
#  edge_importance_weighting: 'Uniform'
  graph_args:
    market: 'HKEXtoSSE'
    relation_path: ./data/HKEXtoSSE/adjmx_amount_HKEXtoSSE.pkl
    strategy: 'uniform'

# test 
phase: test
device: 0
test_batch_size: 64


# seed
seed: 3