#weights: ./work_dir/sp500/best_model.pt
#weights: ./data/t=1/sp500/best_model.pt


weights: ./work_dir/sp500/gru_best_model.pt
#weights: ./work_dir/sp500/lstm_best_model.pt
#weights: ./work_dir/sp500/stgcn_best_model.pt
#weights: ./work_dir/sp500/sastgcn_best_model.pt
#weights: ./work_dir/sp500/rtgcn_best_model.pt
#weights: ./work_dir/sp500/dygcngru_best_model.pt
#weights: ./work_dir/sp500/dygcngruae_best_model.pt
#weights: ./work_dir/sp500/abs_best_model.pt
# feeder
feeder: feeder.feeder.Feeder
#test_feeder_args:
#  data_path: ./data/sp500/test_15_EOD.npy
#  price_path: ./data/sp500/test_15_price.npy
#  label_path: ./data/sp500/test_15_label.pkl
#  adj_path: ./data/sp500/adj_test_15.npz
#=================================================
test_feeder_args:
  data_path: ./data/sp500/test_15_EOD.npy
  price_path: ./data/sp500/test_15_price.npy
  label_path: ./data/sp500/test_15_label.pkl
  adj_path: ./data/sp500/test_15_adj.npz
# model
model: net.benchmarkmodel.GRU
#model: net.benchmarkmodel.LSTM3
#model: net.st_gcn.STGCN
#model: net.SASTGCN.SASTGCN
#model: net.benchmarkmodel.Model_rt_gcn
#model: net.withoutdynet_rtgcn.STGCN_withoutdynet
#model: net.rt_gcn.STGCN
#model: net.rt_gcn.STGCN_wofe
#model: net.rt_gcn.STGCN_withAE

model_args:
  in_channels: 4
  dropout: 0
  hidden: 16
  hidden2: 8
  out_channels: 4
  kernel: 2
  stride: 1
  # edge_importance_weighting: True
#  edge_importance_weighting: 'Uniform'
  graph_args:
    market: 'sp500'
    relation_path: ./data/sp500/adjmx_amount_sp500.pkl
    strategy: 'uniform'

# test 
phase: test
device: 0
test_batch_size: 64


# seed
seed: 3